version: '3.8'

services:

  frontend:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: shoe_shop_frontend
    ports:
      - "8000:80"
    volumes:
      # Mount thư mục FE/static từ host vào thư mục mà Nginx sẽ phục vụ
      - ./FE/static:/usr/share/nginx/html/static:ro # :ro là read-only
    depends_on:
      - backend # Nginx cần backend để proxy request
    networks:
      - shoe_shop_network

  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: shoe_shop_backend
    ports:
      - "8888:8080"
    volumes:
      - ./FE:/app/frontend
    environment:
      - SPRING_THYMELEAF_PREFIX=file:/app/frontend/templates/
      - SPRING_WEB_RESOURCES_STATIC-LOCATIONS=file:/app/frontend/static/
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/shoeshop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=shoeshop
      - SPRING_DATASOURCE_PASSWORD=shoeshop
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate # Hoặc none, update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MariaDBDialect
      - SERVER_FORWARD_HEADERS_STRATEGY=NATIVE
      - SERVER_SERVLET_CONTEXT_PATH=/
      - PRODUCT_SERVICE_URL=http://product-service:8081/api/v1/products

    depends_on:
      db:
        condition: service_healthy
    networks:
      - shoe_shop_network

  #product-service
  product-service:
    build:
      context: ./productService
      dockerfile: Dockerfile
    container_name: shoe_shop_product_service
    ports:
      - "8081:8081" # Map cổng 8081 của product-service container ra cổng 8081 của host
    environment:
      - SPRING_APPLICATION_NAME=product-service
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/shoeshop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=shoeshop # Dùng chung user DB
      - SPRING_DATASOURCE_PASSWORD=shoeshop
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MariaDBDialect # Hoặc MariaDB103Dialect

      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=*
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW-DETAILS=always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - shoe_shop_network

  # database
  db:
    image: mariadb:10.5
    container_name: shoe_shop_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 0810
      MYSQL_DATABASE: shoeshop
      MYSQL_USER: shoeshop
      MYSQL_PASSWORD: shoeshop
    volumes:
      - mariadb_data_volume:/var/lib/mysql
      - ./BE/shoe_shopdb.sql:/docker-entrypoint-initdb.d/init_schema.sql
    ports:
      - "3308:3306"
    networks:
      - shoe_shop_network
    healthcheck: # kiểm tra xem DB đã sẵn sàng chưa
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-ushoeshop", "-pshoeshop"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mariadb_data_volume:

networks:
  shoe_shop_network:
    driver: bridge 
